(BSR) chore(ios): fix iOS CLI
the command

```sh
yarn ios:testing
```

fails with the error

```txt
The file /nix/store/8vpszm9fnh00d6s8m5hi67xrpxnxdd5c-apple-sdk-11.3/Applications/Simulator.app does not exist.
error Command failed: open /nix/store/8vpszm9fnh00d6s8m5hi67xrpxnxdd5c-apple-sdk-11.3/Applications/Simulator.app --args -CurrentDeviceUDID EBDBAC65-9268-4D4A-8785-03A099743F7B
The file /nix/store/8vpszm9fnh00d6s8m5hi67xrpxnxdd5c-apple-sdk-11.3/Applications/Simulator.app does not exist.
.
Error: Command failed: open /nix/store/8vpszm9fnh00d6s8m5hi67xrpxnxdd5c-apple-sdk-11.3/Applications/Simulator.app --args -CurrentDeviceUDID EBDBAC65-9268-4D4A-8785-03A099743F7B
The file /nix/store/8vpszm9fnh00d6s8m5hi67xrpxnxdd5c-apple-sdk-11.3/Applications/Simulator.app does not exist.

    at checkExecSyncError (node:child_process:890:11)
    at Object.execFileSync (node:child_process:926:15)
    at runOnSimulator (/Users/eb/Project/pass-culture/pass-culture-app-native/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js:219:28)
    at Object.runIOS [as func] (/Users/eb/Project/pass-culture/pass-culture-app-native/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js:144:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.handleAction (/Users/eb/Project/pass-culture/pass-culture-app-native/node_modules/@react-native-community/cli/build/index.js:111:9)
```

or

```txt
error: tool 'xcodebuild' not found
```