(BSR) chore(dependencies): update devbox (#7864)
* (BSR) chore(dependencies): update devbox

try to avoid the following error

```txt
/nix/store/559pz0w6zlvw8yyxah9s10fhaz400vaj-stdenv-darwin/setup: line 138: pop_var_context: head of shell_variables not a function context
```

which need to re-run `direnv allow`

* remove legacy SSL variables to make web working

Cédric had this error when trying the web

```txt
 ERROR  15:10:43 [vite] http proxy error: /native/v1/settings                                                                                                           15:10:43
Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
    at TLSSocket.emit (node:events:514:28)
    at TLSSocket._finishInit (node:_tls_wrap:1085:8)
    at ssl.onhandshakedone (node:_tls_wrap:871:12)

 ERROR  15:10:43 [vite] http proxy error: /native/v1/subcategories/v2                                                                                                   15:10:43
Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
    at TLSSocket.emit (node:events:514:28)
    at TLSSocket._finishInit (node:_tls_wrap:1085:8)
    at ssl.onhandshakedone (node:_tls_wrap:871:12)

 ERROR  15:10:48 [vite] http proxy error: /native/v1/settings                                                                                                           15:10:48
Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
    at TLSSocket.emit (node:events:514:28)
    at TLSSocket._finishInit (node:_tls_wrap:1085:8)
    at ssl.onhandshakedone (node:_tls_wrap:871:12)
```