(BSR) build(ios): fix iOS
Before this commit
==================

When doing the following command

```sh
yarn ios:prod
```

It fails with the error

```txt
warn Package react-native-flipper contains invalid configuration: "dependency.platforms.ios.project" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info Found Xcode workspace "PassCulture.xcworkspace"
info No booted devices or simulators found. Launching first available simulator...
The file /nix/store/2y71rl5mnazwnpwpcq07xx97jl7sy5lh-apple-sdk-11.3/Applications/Simulator.app does not exist.
error Command failed: open /nix/store/2y71rl5mnazwnpwpcq07xx97jl7sy5lh-apple-sdk-11.3/Applications/Simulator.app --args -CurrentDeviceUDID EBDBAC65-9268-4D4A-8785-03A099743F7B
The file /nix/store/2y71rl5mnazwnpwpcq07xx97jl7sy5lh-apple-sdk-11.3/Applications/Simulator.app does not exist.
.
Error: Command failed: open /nix/store/2y71rl5mnazwnpwpcq07xx97jl7sy5lh-apple-sdk-11.3/Applications/Simulator.app --args -CurrentDeviceUDID EBDBAC65-9268-4D4A-8785-03A099743F7B
The file /nix/store/2y71rl5mnazwnpwpcq07xx97jl7sy5lh-apple-sdk-11.3/Applications/Simulator.app does not exist.

    at checkExecSyncError (node:child_process:890:11)
    at Object.execFileSync (node:child_process:926:15)
    at runOnSimulator (/Users/eb/Project/pass-culture/pass-culture-app-native/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js:219:28)
    at Object.runIOS [as func] (/Users/eb/Project/pass-culture/pass-culture-app-native/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js:144:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.handleAction (/Users/eb/Project/pass-culture/pass-culture-app-native/node_modules/@react-native-community/cli/build/index.js:111:9)
```

When looking for XCode path, with the following command

```sh
xcode-select --print-path
```

It outputs this

```txt
/nix/store/2y71rl5mnazwnpwpcq07xx97jl7sy5lh-apple-sdk-11.3
```

Because installing JDK througth DevBox set the following variable environment

```sh
DEVELOPER_DIR=/nix/store/2y71rl5mnazwnpwpcq07xx97jl7sy5lh-apple-sdk-11.3
```

XCode-select seems to display this variable when set

The following test command

```sh
DEVELOPER_DIR=toto xcode-select --print-path
```

Displays

```txt
toto
```

After this commit
=================

```sh
xcode-select --print-path
```

```txt
/Applications/Xcode.app/Contents/Developer
```