(BSR) chore(ios): fix iOS CLI (#7938)
* avoid CocoaPods warning

```txt
WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:

    export LANG=en_US.UTF-8
```

* (BSR) chore(ios): fix iOS CLI

the command

```sh
yarn ios:testing
```

fails with the error

```txt
The file /nix/store/8vpszm9fnh00d6s8m5hi67xrpxnxdd5c-apple-sdk-11.3/Applications/Simulator.app does not exist.
error Command failed: open /nix/store/8vpszm9fnh00d6s8m5hi67xrpxnxdd5c-apple-sdk-11.3/Applications/Simulator.app --args -CurrentDeviceUDID EBDBAC65-9268-4D4A-8785-03A099743F7B
The file /nix/store/8vpszm9fnh00d6s8m5hi67xrpxnxdd5c-apple-sdk-11.3/Applications/Simulator.app does not exist.
.
Error: Command failed: open /nix/store/8vpszm9fnh00d6s8m5hi67xrpxnxdd5c-apple-sdk-11.3/Applications/Simulator.app --args -CurrentDeviceUDID EBDBAC65-9268-4D4A-8785-03A099743F7B
The file /nix/store/8vpszm9fnh00d6s8m5hi67xrpxnxdd5c-apple-sdk-11.3/Applications/Simulator.app does not exist.

    at checkExecSyncError (node:child_process:890:11)
    at Object.execFileSync (node:child_process:926:15)
    at runOnSimulator (/Users/eb/Project/pass-culture/pass-culture-app-native/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js:219:28)
    at Object.runIOS [as func] (/Users/eb/Project/pass-culture/pass-culture-app-native/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js:144:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.handleAction (/Users/eb/Project/pass-culture/pass-culture-app-native/node_modules/@react-native-community/cli/build/index.js:111:9)
```

or

```txt
error: tool 'xcodebuild' not found
```

* help XCode to find clang to be able to build iOS in CLI

without this, we can have this kind of error

```
▸ Running script '[CP-User] [Hermes] Replace Hermes for the right configuration, if needed'

❌  error: interrupted by the user

▸ Running script '[CP-User] Generate Specs'

❌  error: interrupted by the user

▸ Compiling yuv_sse2.c

❌  clang: error: unknown argument: '-index-store-path'

❌  clang: error: no such file or directory: '/Users/cedric/Library/Developer/Xcode/DerivedData/PassCulture-gijlwnrcorivwefryscvnwjcysaq/Index.noindex/DataStore'

▸ Compiling yuv_neon.c

❌  clang: error: unknown argument: '-index-store-path'

❌  clang: error: no such file or directory: '/Users/cedric/Library/Developer/Xcode/DerivedData/PassCulture-gijlwnrcorivwefryscvnwjcysaq/Index.noindex/DataStore'

▸ Compiling yuv_sse41.c

❌  clang: error: unknown argument: '-index-store-path'

❌  clang: error: no such file or directory: '/Users/cedric/Library/Developer/Xcode/DerivedData/PassCulture-gijlwnrcorivwefryscvnwjcysaq/Index.noindex/DataStore'

▸ Compiling yuv_mips_dsp_r2.c

❌  clang: error: unknown argument: '-index-store-path'

❌  clang: error: no such file or directory: '/Users/cedric/Library/Developer/Xcode/DerivedData/PassCulture-gijlwnrcorivwefryscvnwjcysaq/Index.noindex/DataStore'

▸ Compiling yuv_mips32.c

❌  clang: error: unknown argument: '-index-store-path'

❌  clang: error: no such file or directory: '/Users/cedric/Library/Developer/Xcode/DerivedData/PassCulture-gijlwnrcorivwefryscvnwjcysaq/Index.noindex/DataStore'

▸ Compiling yuv.c

❌  clang: error: unknown argument: '-index-store-path'

❌  clang: error: no such file or directory: '/Users/cedric/Library/Developer/Xcode/DerivedData/PassCulture-gijlwnrcorivwefryscvnwjcysaq/Index.noindex/DataStore'

▸ Compiling webp_enc.c

❌  clang: error: unknown argument: '-index-store-path'

❌  clang: error: no such file or directory: '/Users/cedric/Library/Developer/Xcode/DerivedData/PassCulture-gijlwnrcorivwefryscvnwjcysaq/Index.noindex/DataStore'

▸ Running script '[CP] Copy XCFrameworks'
    Run script build phase '[CP-User] [Hermes] Replace Hermes for the right configuration, if needed' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'hermes-engine' from project 'Pods')
    Run script build phase 'Start Packager' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'PassCulture' from project 'PassCulture')
    Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'PassCulture' from project 'PassCulture')
    Run script build phase 'Upload Debug Symbols to Sentry' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'PassCulture' from project 'PassCulture')
    Run script build phase '[CP-User] [RNFB] Core Configuration' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'PassCulture' from project 'PassCulture')

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

error Failed to build iOS project. "xcodebuild" exited with error code '65'. To debug build logs further, consider building your app with Xcode.app, by opening 'PassCulture.xcworkspace'.
```

* fix iOS build

* fix iOS build

* ios-deploy is needed to run the app on real iPhone

* accept Apple license for Android Studio

* remove legacy VSCode setting

This modal was displayed when hovering this settings

```txt
Ce paramètre a une étendue d’application et ne peut être défini que dans le fichier de paramètres utilisateur.
```