FlushPromises after each test
This is to prevent CI from randomly failing due to:

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.